[project]
name = "name2gender-roformer-train"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.0.0",
    "deeplotx>=0.9.9",
    "tensorboard>=2.20.0",
    "torch==2.7.0",
]
